### ISSUE TITLE
feature: 有很多相关建议，但是也看到过codesandbox本身就有开源此类的插件，不知道相关功能会不会重复了

### ISSUE THREAD

**Issue by jeryqwq** [zh-lx/codeplayer#16]
1. 支持常用文件预览和使用,如: mp3,mp4,pdf,img等，也能使用import语法引入资源并使用。
2.  支持同时打开多文件
3.  相关代码提示
4. 支持右侧预览区自定义分辨率
5. 支持代码区控制台
6. 支持vue,react相关的dev-tool

**Comment by zh-lx** [comment]
感谢阶段，目前还处于开发测试阶段，预计1-2个月内会逐步完善这些功能



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月02日 19:40 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [zh-lx/code-sandbox] feature: 有很多相关建议，但是也看到过codesandbox本身就有开源此类的插件，不知道相关功能会不会重复了 (Issue #16) |

支持常用文件预览和使用,如: mp3,mp4,pdf,img等，也能使用import语法引入资源并使用。
支持同时打开多文件
相关代码提示
支持右侧预览区自定义分辨率
支持代码区控制台
支持vue,react相关的dev-tool
